# OpenGL visualization for an interactive G4XRTube session.
/vis/open OGL 1400x1000-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/drawVolume
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector 1 0 0
/vis/viewer/set/lightsVector 1 0 0
/vis/viewer/zoom 1.5
/vis/viewer/set/style wireframe
/vis/viewer/set/background 1 1 1
/vis/scene/add/axes 0 0 0 20 cm

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/scene/endOfEventAction accumulate -1

/vis/viewer/set/autoRefresh true
/vis/verbose warnings
/vis/viewer/flush
